# Generated by Django 3.0.3 on 2020-02-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('order_placed', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('clothtype', models.CharField(max_length=50)),
                ('choose_service', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pick_up', 'Picked Up'), ('delivered', 'Delivered'), ('processing', 'Processing'), ('verified', 'Verified'), ('cancelled', 'Cancelled'), ('ready_to_deliver', 'Ready to be deliverd'), ('transaction_completed', 'Transaction Completed')], default='DEFAULT VALUE', max_length=50)),
                ('order_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(null='True')),
            ],
        ),
    ]
